### ISSUE TITLE
`$ npm run test` fails

### ISSUE THREAD

**Issue by shgoren** [yeahthisisrob/quicksight-power-tools#1]
Seems like the `test` script is missing.

This is the output of `$ npm run`

```
➜  quicksight-power-tools git:(main) ✗ npm run
Lifecycle scripts included in quicksight-power-tools@1.0.0:
  start
    webpack serve --config webpack.config.mjs --mode development --open
available via `npm run-script`:
  build
    webpack --config webpack.config.mjs --mode production
  format
    prettier --write "src/**/*.{js,jsx,ts,tsx,json,css,md}"
```

**Comment by yeahthisisrob** [comment]
Thanks @shgoren - There are no unit tests and they need to be created (and the script added). This is one of the blockers of getting this extension published in the chrome store. 

I've removed the tests section from the README.
