### ISSUE TITLE
Chrome dev extention installation instructions are missing

### ISSUE THREAD

**Issue by shgoren** [yeahthisisrob/quicksight-power-tools#2]
The ReadMe mentions:
`Follow the Installation steps above to load the unpacked extension in Chrome using your local build.`

yet instructions are not provided.

**Comment by yeahthisisrob** [comment]
Thanks for finding this @shgoren - I will update the README to have instructions similar to those found in the beta release notes https://github.com/yeahthisisrob/quicksight-power-tools/releases/tag/v1.0.0-beta

**Comment by shgoren** [comment]
For others -
That means:

1. Go to `chrome://extensions/` in your Chrome browser.
2. Enable `Developer mode` in the top right corner.
3. Click `Load unpacked` and select the `dist` folder that was created after running `npm run build`.
